### ISSUE TITLE
A token was supplied.\nIf you are using a token, you need to pass it like ...trigger/invoke?token=TOKENHERE\nIf you are not using a token

### ISSUE THREAD

**Issue by cf1998** [jenkinsci/generic-webhook-trigger-plugin#302] opened 2024-04-02 09:46 UTC
### Jenkins and plugins versions report

I have set up the pipeline, but the webhook is reporting the following error:
```shell
curl -X POST -H "Content-Type: application/json" -d '{"ref": "refs/heads/master", "before": "old_commit_id", "after": "new_commit_id"}' http://10.0.53.73:8080/generic-webhook-trigger/invoke?token=12345678
{"jobs":null,"message":"Did not find any jobs with GenericTrigger configured!\nA token was supplied.\nIf you are using a token, you need to pass it like ...trigger/invoke?token=TOKENHERE\nIf you are not using a token, you need to authenticate like http://user:passsword@example.org/generic-webhook...\n"}
```

**Comment by tomasbjerre** [comment] 2024-04-02 09:49
Closing this issue because there is nothing in it that can be investigated. Open new issue and provide your exact configuration as asked for in the issue template.

**Comment by cf1998** [comment] 2024-04-02 09:50
pipeline：
```shell
pipeline {
    agent any
    triggers {
        GenericTrigger(
             genericVariables: [
                 [key: 'ref', value: '$.ref'],
                 [key: 'before', value: '$.before'],
                 [key: 'after', value: '$.after']
             ],
             causeString: 'Triggered on $ref',
             token: '12345678',
             printContributedVariables: true,
             printPostContent: true
        )
    }
    stages {
        // your stages here
    }
}
```
The free-style configuration is normal.

**Closed by tomasbjerre** 2024-04-02 09:49 UTC
Labels: bug

**Comment by juananinca** [comment] 2024-04-12 14:01
I recently updated the plugin to the 2.1.1 version and new jobs created after the plugin update are not triggered by the plugin.
The plugin response is the same that @cf1998 mentioned:

`{"jobs":null,"message":"Did not find any jobs with GenericTrigger configured!\nA token was supplied.\nIf you are using a token, you need to pass it like ...trigger/invoke?token=TOKENHERE\nIf you are not using a token, you need to authenticate like http://user:passsword@example.org/generic-webhook...\n"}`

I must say that older jobs created before the plugin update work fine, the problem is with the new ones.
The only way I managed to get the new ones working was restarting jenkins. No new created job will be triggered without restarting Jenkins.

**Comment by tomasbjerre** [comment] 2024-04-12 14:04
Are you using the cache?

**Comment by juananinca** [comment] 2024-04-12 14:14
yes, I set a 60 min as ttl.

**Comment by tomasbjerre** [comment] 2024-04-12 14:17
> yes, I set a 60 min as ttl.

That means you have to disable the chache, wait up to 60 minutes or restart Jenkins.

**Comment by juananinca** [comment] 2024-04-12 14:20
Perfect, I will check that.

Thank you for the quick response!
