### ISSUE TITLE
Request: Supporting of JSON header without flattening 

### ISSUE THREAD

**Issue by anilkumars** [jenkinsci/generic-webhook-trigger-plugin#30] opened 2018-01-03 02:38 UTC
Needed JSON header as it is without flattening the content of JSON.

**Comment by tomasbjerre** [comment] 2018-01-03 12:27
Released in 1.22.

To just use the expression `$` and there will be a variable containing all JSON.

Open issue again if not working.

**Closed by tomasbjerre** 2018-01-03 12:27 UTC

**Comment by anilkumars** [comment] 2018-01-03 18:17
Thanks tomasbjerre for quick reply,

I tried Version 1.23:

Used $ in expression, but didnt see any contributing variables.

Thanks,
Anil

**Comment by tomasbjerre** [comment] 2018-01-03 18:31
This was released in 1.22.

What exactly does your configuration look like? Can you supply a curl
command to reproduce this? See example in the readme.

Den 3 jan. 2018 19:17 skrev "Anil Kumar Singamaneni" <
notifications@github.com>:

Thanks tomasbjerre for quick reply,

I tried Version 1.23:

Used $ in expression, but didnt see any contributing variables.

Thanks,
Anil

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/jenkinsci/generic-webhook-trigger-plugin/issues/30#issuecomment-355085623>,
or mute the thread

**Comment by anilkumars** [comment] 2018-01-03 18:41
Hi Tomas, 

Thanks for quick reply.


**Curl Command like below:**
   curl -u "admin:admin" -H "Content-Type: application/json" -X POST -d '{
     "search_name":"Test",
     "owner": "service_virtual_infrastructure",
     "result":    {
         "event_time": "Oct  9 15:04",
     },
       "test": "Test"
   }'  http://localhost:8080/generic-webhook-trigger/invoke?token=ulnet_remediation

**Jenkins Job Configuration like below:**

Variable test

Expression $



Thanks,
Anil

**Comment by tomasbjerre** [comment] 2018-01-03 19:53
You have some invalid characters and an extra `,` at the end of the line `event_time`.

This works for me:

```
curl -u "admin:admin" -H "Content-Type: application/json" -X POST -d '{
 "search_name": "Test",
 "owner": "service_virtual_infrastructure",
 "result":     {
  "event_time": "Oct  9 15:04"
 },
 "test": "Test"
}'  http://localhost:8080/generic-webhook-trigger/invoke?token=ulnet_remediation
```

**Comment by anilkumars** [comment] 2018-01-03 20:02
Thanks Much Tomas,

It worked after correcting the input Json as per your suggestion.
Appreciate your help.

I see same log message:

{
 "search_name": "Test",
 "owner": "service_virtual_infrastructure",
 "result":     {
  "event_time": "Oct  9 15:04"
 },
 "test": "Test"
}


Contributing variables:

    test_search_name = Test
    test = {"search_name":"Test","owner":"service_virtual_infrastructure","result":{"event_time":"Oct  9 15:04"},"test":"Test"}
    test_result_event_time = Oct  9 15:04
    test_owner = service_virtual_infrastructure
    test_test = Test
